### ISSUE TITLE
Karavan Designer after start up getting the 404

### ISSUE THREAD

**Issue by kondetiramanakumar** [apache/camel-karavan#1212]
<img width="929" alt="image" src="https://github.com/apache/camel-karavan/assets/14121796/ab5ba3bb-8a7a-4bdd-b1d2-76a535fd9ebc">
please help me out from  this????

**Comment by kondetiramanakumar** [comment]
@mgubaidullin please help me out  from this errors while launching the karavan designer.

@mgubaidullin One more thing AtlasMap Integration is available in karavan. please reply???

**Comment by mgubaidullin** [comment]
There is no 'Atlasmap feature' in Karavan.
And we are not planning to integrate with Atlasmap because project is inactive for more than a year.


<img width="1024" alt="Screenshot 2024-04-02 at 11 42 18 AM" src="https://github.com/apache/camel-karavan/assets/1379213/e9fc9818-e124-4988-949d-72e2805da108">
