### ISSUE TITLE
The delete button for a route should be at route start(from)

### ISSUE THREAD

**Issue by cgballance** [apache/camel-karavan#228]
In order to delete a route, a mouseover on the word "Route" at the top of the route is used to put the delete button in view at the upper right of the enclosing div.  The first step in the route should probably have the delete button to the immediate upper right of it.
In any case, the ux is hindered, as it is anchored too far away and if the view is scrollable, will wind up becoming visible outside of the viewable area.
An alternate "fix" would be to put it to the immediate upper right of the "Right" literal.

**Comment by mgubaidullin** [comment]
Route does not have steps starting from Camel 3.16.0 
In an example below route starts **from** `direct` and all steps are in the **from** scope
Route does not work without **from** that's why from can'd be deleted and there is no delete button.


<img width="343" alt="Screen Shot 2022-03-23 at 7 57 41 AM" src="https://user-images.githubusercontent.com/1379213/159694041-08eab10e-479c-4238-bf95-4c9b89359c4d.png">


<img width="312" alt="Screen Shot 2022-03-23 at 7 57 27 AM" src="https://user-images.githubusercontent.com/1379213/159694029-d7eeded6-b7ee-406c-b738-adf8cbd43581.png">

**Comment by cgballance** [comment]
Deleting the 'from' should be a/the way to delete the route.  The dialog could state the repercussions.
