### ISSUE TITLE
Allow message components to be selectable from the UI

### ISSUE THREAD

**Issue by 00xE8** [apache/camel-karavan#429]
For citizen integrators, a great feature available in Azure LogicApps, is the ability to construct message schemas visually, as shown here [https://docs.microsoft.com/en-us/azure/logic-apps/media/logic-apps-perform-data-operations/send-email-parse-json-action.png](url)

I would be happy to work on this, is there a starting guide?

**Comment by mgubaidullin** [comment]
It is not that simple, because Camel keep data in the message container (Exchange).
Exchange contains message body, headers, etc. 
Body and header values are Java objects and might contain data in various formats (XML, JSON, YAML, binary, etc)
Visual Constructor for them is a huge project.
I don't even know where to start

**Comment by mgubaidullin** [comment]
Data mapping is in RoadMap for 2023 https://camel.apache.org/blog/2022/10/camel-karavan-roadmap/
