### ISSUE TITLE
Rewrite Karavan Designer to use Functional Components and State

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#836]

**Comment by stefanhuber** [comment]
Is this process already ongoing?

**Comment by mgubaidullin** [comment]
@stefanhuber yes

**Comment by stefanhuber** [comment]
Ok is there already a branch for that? If you define how, I might be able to help you with some of the components.

Firstly, thank you for providing such a great tool. Some first thoughts/obvservations, which I made when going through the code base:
- It might make sense to create a folder for each component and also add css (instead of one big karavan.css). 
- Some components are quite big (e.g, [RestDesigner](https://github.com/apache/camel-karavan/blob/main/karavan-designer/src/designer/rest/RestDesigner.tsx)), it might be possible to split them into smaller ones
- Use 2 spaces for indentation might help ([example](https://github.com/apache/camel-karavan/blob/f6f77ea88b364b6ba7e479327964e1092b4804fc/karavan-designer/src/designer/beans/BeansDesigner.tsx#L130)), it is generally used with javascript
- Adding testing to the component folder directly
- Starting the development server with `npm start` takes a long time, vite would improve this drastically
- It might makes sense to use storybook for developing components in isolation
- Why use react layout components, if the same is possible with css flexbox, just with less code and better performance? ([example](https://github.com/apache/camel-karavan/blob/f6f77ea88b364b6ba7e479327964e1092b4804fc/karavan-designer/src/DesignerPage.tsx#L111))
- One could create a custom hook in react instead of an additional library (`lodash.debounce`) for debounding ([example](https://dev.to/rajeshroyal/how-to-make-a-custom-debounce-hook-in-react-js-4gcc))

**Comment by jasham** [comment]
Greetings,

This library is very useful. I am using this library for one of my personal projects, but the code and logic are currently written in Typescript and I am trying to convert it to JSX but facing some issues because I am not that good in Typescript. It will be very helpful if the JSX version is available for this.

**Thanks,
Jasham**
