### ISSUE TITLE
Karavan Space - Cannot expand Security parameters on as2 component when its at bottom screen

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#880]
<img width="2005" alt="Screenshot 2023-09-01 at 22 07 04" src="https://github.com/apache/camel-karavan/assets/477100/f9958b68-3731-400f-b6da-50a32c42db31">

**Comment by davsclaus** [comment]
In the bottom right corner, you cannot click "Security parameters" to have it expanded and show its options.

**Comment by mgubaidullin** [comment]
Fixed

**Comment by dpalinic** [comment]
Hi @mgubaidullin , thanks for your effort building and maintaining such a cool tool. 

Unfortunately, we can reproduce this issue in 4.1 as well. It seems to be a big user facing issue since many parameters are not accessible. Any chance to re-test it one more time?

![image001](https://github.com/apache/camel-karavan/assets/801314/ea9c3445-cb04-4e98-abec-5c879e828c05)

**Comment by dpalinic** [comment]
Actually I see this is for Karavan Space, but I'm referring to Karavan Web. I'll open a new defect there.
