### ISSUE TITLE
How to use embedded infinispan instead of remote infinispan?

### ISSUE THREAD

**Issue by manali-jambhale** [apache/camel-karavan#926]
In recent versions of karavan remote infinispan on kubernetes is being used. How can I use the old local mode of infinispan instead of remote mode?

**Comment by mvolf** [comment]
I've also noticed this. This causes issues when trying to run Karavan in live dev env with quarkus.
In this case web app stays indefinitely on the "Waiting for services screen", since it can't seem to connect to remote Infinispan.
In the logs the same message keeps occurring constantly:
`INFO  [org.apa.cam.kar.inf.InfinispanService] (vert.x-worker-thread-1) InfinispanService is starting in remote mode`

**Comment by mgubaidullin** [comment]
1. embedded infinispan is not supported by quarkus
2. for local development start karavan with docker and karavan will deploy infinispan in docker

**Comment by mvolf** [comment]
Thanks for the answer @mgubaidullin. Can you please clarify how to start karavan with docker using the karavan jar built from the source (to include and test changes made in the code)?

**Comment by mgubaidullin** [comment]
@mvolf I start Karavan while developing using the following command:
```mvn clean quarkus:dev -Dquarkus.profile=public -Dkaravan.infinispan.hosts=localhost:11222 -Dkaravan.git-install-gitea=true -Dkaravan.git-repository=http://localhost:3000/karavan/karavan.git```
